import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavItems from "@/components/NavItems";
import ClientWrapper from "@/components/clientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       


          {/* Content */}
          <ClientWrapper>
          <div className="relative z-10">
            <div className="fixed h-[100vh] top-0 left-1/2 z-50 -translate-x-1/2">
              <NavItems />
            </div>

            <main>{children}</main>
          </div>
          </ClientWrapper>
         

      </body>
    </html>
  );
}
